title: VITA (Vehicle-based Intelligent Technology for Atmosphere research) Project Cookbooks
author: Project VITA Team
logo: 
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - html_image
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - replacements
    - smartquotes
    - substitution
html:
  comments:
    hypothesis: true
repository:
  url: https://github.com/EVS-ATMOS/vita  # Online location of your book
  path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  jupyterhub_url:
  notebook_interface:
